### ISSUE TITLE
Inserting zero entries to a part table

### ISSUE THREAD

**Issue by boazmohar** [mattbdean/Helium#47]
If I have a master__part table (e.g. `session__trial`), if I try to insert only to the `session` table with nothing to the `trial` part table I get the following error:
``` bash
{ message: 'generated invalid SQL',
  data: { session: [ [Object] ], session__trial: [] } }
{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
    at Query.Sequence._packetToError (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at PoolConnection.query (/Users/moharb/Documents/Repos/Helium/node_modules/mysql/lib/Connection.js:208:25)
    at /Users/moharb/Documents/Repos/Helium/node_modules/promise-mysql/lib/helper.js:16:24
    at Promise._execute (/Users/moharb/Documents/Repos/Helium/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/moharb/Documents/Repos/Helium/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/moharb/Documents/Repos/Helium/node_modules/bluebird/js/release/promise.js:79:10)
    at PoolConnection.promiseCallback (/Users/moharb/Documents/Repos/Helium/node_modules/promise-mysql/lib/helper.js:6:10)
    at poolConnection.connection.query (/Users/moharb/Documents/Repos/Helium/node_modules/promise-mysql/lib/connection.js:64:28)
    at QueryHelper.<anonymous> (/Users/moharb/Documents/Repos/Helium/dist/db/query-helper.js:24:54)
    at Generator.next (<anonymous>)
    at /Users/moharb/Documents/Repos/Helium/dist/db/query-helper.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/moharb/Documents/Repos/Helium/dist/db/query-helper.js:3:12)
    at QueryHelper.execute (/Users/moharb/Documents/Repos/Helium/dist/db/query-helper.js:22:16)
    at SchemaDao.<anonymous> (/Users/moharb/Documents/Repos/Helium/dist/routes/api/schemas/schema.dao.js:177:39)
    at Generator.next (<anonymous>)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\' at line 1',
  sqlState: '42000',
  index: 0,
  sql: 'INSERT INTO `boazmohar_experiment`.`session__trial`' }
PUT /api/v1/schemas/boazmohar_experiment/data 500 104.906 ms - 3155
```

If I add a single entry to the `trial` table the form works, also the same inset to the `session` table works from the dj python API.

**Comment by mattbdean** [comment]
Can you take a screenshot of your browser right before you hit submit?

**Comment by boazmohar** [comment]
<img width="1345" alt="screenshot 2018-01-06 12 22 44" src="https://user-images.githubusercontent.com/9434009/34642145-56564046-f2dc-11e7-9426-3858bd992bbc.png">

**Comment by mattbdean** [comment]
When I try to reproduce it says there's a duplicate key, could you delete conflicting data in Session/Session.Trial?

**Comment by boazmohar** [comment]
Try now

**Comment by mattbdean** [comment]
This is an issue with the server. For whatever reason it tries to produce an `INSERT` query even though there is no data to insert. Should be a pretty simple fix. I can reproduce this bug on any master table by not messing with any part table data.
